project/models.py
# project/models.py


import datetime
from time import time
from main.forms import SEX
from project import db, bcrypt
from flask import jsonify


class User(db.Model):

    __tablename__ = "users"

    # USER CREDENTIAL + LOGIN RELATED FIELDS
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)
    # OTHER USER FIELDS
    username = db.Column(db.String(80), unique=True, nullable=True)
    first_name = db.Column(db.String(80),unique=False, nullable=True)
    last_name = db.Column(db.String(80), unique=False, nullable=True)
    age = db.Column(db.String(80), unique=False, nullable=True)
    sex = db.Column(db.String(1), nullable=True)
    image = db.Column(db.String(100), nullable=True)
    high_score = db.Column(db.Integer, nullable=True, default=0)
    tdollars = db.Column(db.Integer, nullable=True, default=0)

    def __init__(self, email, password, username, first_name, last_name, age, confirmed, sex=0, confirmed_on=None, admin=False):
        self.email = email
        self.password = bcrypt.generate_password_hash(password)
        self.registered_on = datetime.datetime.now()
        self.admin = admin
        self.confirmed = confirmed
        self.confirmed_on = confirmed_on
        self.username = username
        self.first_name = first_name
        self.last_name = last_name
        self.age = age
        self.sex = sex
        # self.id = User.generate_user_id()

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def get_sex_display(self):
        return SEX[self.sex]

    @staticmethod
    def generate_user_id():
        new_id = time()
        new_id = str(long(new_id))
        return long(new_id)

    def __repr__(self):
        return 'Email:{}, Username:{}, First Name:{}, Last Name:{}'.format(self.email,self.username,self.first_name,self.last_name)

    def get_image_url(self):
        return '/uploads/{0}'.format(self.image)

    def to_json(self):
        return json.dumps({
            "id": self.id,
            "email":self.email,
            "username": self.username,
            "first_name":self.first_name,
            "last_name":self.last_name,
            "image": "...",
            "sex": self.get_sex_display(),
            "age": self.age,
            "profile_registered_on": self.registered_on.strftime("%Y-%m-%d"),
            "high_score": self.high_score,
            "tdollars": self.tdollars,
            })

    def get_sex_display(self):
        return SEX[self.sex]

project/main/forms.py
# coding=utf-8;

from flask_wtf import Form
from wtforms import StringField, IntegerField, FileField, SelectField
from wtforms.validators import InputRequired, Length, ValidationError

SEX = {'0': 'male','1': 'female'}
SEX_CHOICES = list((k, v) for k, v in SEX.iteritems())

project/user/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField, IntegerField, SelectField
from wtforms.validators import DataRequired, InputRequired, Email, Length, EqualTo
from project.models import User

SEX = {'0': 'Male','1': 'Female'}
SEX_CHOICES = list((k, v) for k, v in SEX.iteritems())

class LoginForm(Form):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])


class SignupForm(Form):
    username = TextField('First Name',validators=[DataRequired(), Length(max=80)])
    first_name = TextField('First Name',validators=[DataRequired(), Length(max=80)])
    last_name = TextField('Last Name',validators=[DataRequired(), Length(max=80)])
    age = IntegerField('Age', validators=[InputRequired()])
    sex = SelectField('Sex', choices=SEX_CHOICES,validators=[])
    # image = pass
    email = TextField('email',validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField('password',validators=[DataRequired(), Length(min=6, max=25)])
    confirm = PasswordField('Repeat password',validators=[DataRequired(),EqualTo('password', message='Passwords must match.')])

    def validate(self):
        # initial_validation = super(SignupForm,self).validate()
        # if not initial_validation:
        #     return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        return True


class ChangePasswordForm(Form):
    password = PasswordField(
        'password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Repeat password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask_mail import Mail
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.sqlalchemy import SQLAlchemy




app = Flask(__name__)

app.config.from_object(os.environ['APP_SETTINGS'])

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)


####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)


####################
#### flask-login ####
####################

from project.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask.ext.login import login_required


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################

@main_blueprint.route('/')
@login_required
def home():
    return render_template('main/index.html')

@main_blueprint.route('/platformgame')
def game1():
    return render_template('main/platformer/index.html')

@main_blueprint.route('/spacegame')
def game2():
    return render_template('main/spaceinvader/index.html')

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################

import datetime
from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask.ext.login import login_user, logout_user, login_required, current_user

from project.models import User
from project import db, bcrypt
from .forms import LoginForm, SignupForm, ChangePasswordForm
from project.token import generate_confirmation_token, confirm_token
from project.email import send_email

from project.decorators import check_confirmed

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm(request.form)
    if form.validate_on_submit():
        # return render_template('dump.html',value=form.email.data)
        user = User(email=form.email.data,password=form.password.data,confirmed=False,admin=False,first_name=form.first_name.data,last_name=form.last_name.data,username=form.username.data,sex=form.sex.data,age=form.age.data)
        # admin=True,confirmed=True,confirmed_on=datetime.datetime.now(), first_name="Administrator", last_name="User",age=23
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email',token=token, _external=True)
        html = render_template('user/activate.html',confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email,subject, html)
        login_user(user)
        flash('A confirmation email has been sent via email.', 'success')
        return redirect(url_for("user.unconfirmed"))
    return render_template('user/signup.html',form=form)

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('Welcome.', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)

@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.','success')
    else:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!','success')
    return redirect(url_for('main.home'))

@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('main.home')
    flash('Please confirm your account!','warning')
    return render_template('user/unconfirmed.html')

@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html',confirm_url=confirm_url)
    subject = "Please confirm your email address"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been set', 'success')
    return redirect(url_for('user.unconfirmed'))

@user_blueprint.route('/profiles')
@login_required
def profiles():
    return render_template('dump.html', value=None)

project/templates/user/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

project/templates/user/login.html
{% extends "_base.html" %}

{% block content %}

<h1>Please login</h1>
<br>
<form class="form-login" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ form.email(placeholder="email") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Sign in!</button>
  <br><br>
  <p>Need to <a href="/signup">Signup</a>?</p>
</form>

{% endblock %}

project/templates/user/profile.html
{% extends "_base.html" %}

{% block content %}

<h1>Your Profile</h1>
<br>

{% if current_user.is_authenticated() %}
  <p>
  <ul>
    <li>Email: {{current_user.email}}</li>
    <li>{{ current_user }}</li>
  </ul>
  </p>
{% endif %}

<h2>Change Password</h2>
<br>
<form class="form-reset" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
    {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.confirm(placeholder="confirm") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Update</button>
</form>


{% endblock %}

project/templates/user/signup.html
{% extends "_base.html" %}

{% block content %}

<h1>Please Signup</h1>
<br>
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
  {{ form.username(placeholder="Username") }}
    <span class="error">
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.first_name(placeholder="First Name") }}
    <span class="error">
      {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.last_name(placeholder="Last Name") }}
    <span class="error">
      {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.age(placeholder="Age") }}
    <span class="error">
      {% if form.age.errors %}
        {% for error in form.age.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.sex(placeholder="Sex") }}
    <span class="error">
      {% if form.sex.errors %}
        {% for error in form.sex.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.email(placeholder="Email") }}
    <span class="error">
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.password(placeholder="Password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.confirm(placeholder="Confirm Password") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Signup</button>
  <br><br>
  <p>Already have an account? <a href="/login">Sign in</a>.</p>
</form>
{% endblock %}

project/templates/user/unconfirmed.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (your spam folder) - should have received an email witha confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('user.resend_confirmation') }}">Resend</a></p>

{% endblock %}